export default (syntax) => ({
  name: "Pan",
  type: "light",
  colors: {
    //  // ---------------------------
    // Editor Base Colors
    // ---------------------------
    "selection.background": "#169fb155",
    "descriptionForeground": "#929ea0",
    errorForeground: "#ff2d19",
    "widget.shadow": "#00000055",
    "editor.background": "#fff7ec",
    "editorLineNumber.foreground": "#ffaa7665",
    "editorLineNumber.activeForeground": "#ffaa76",
    "editorCursor.foreground": "#674c26",
    // ---------------------------
    // Badge
    // ---------------------------
    "badge.background": "#735A3C",
    "badge.foreground": "#fff7ec",
    // ---------------------------
    // Activity Bar
    // ---------------------------
    "activityBar.background": "#ffaa76",
    "activityBar.dropBackground": "#735A3C65",
    "activityBar.foreground": "#735A3C",
    "activityBar.border": "#ff976700",
    "activityBarBadge.background": "#735A3C",
    "activityBarBadge.foreground": "#fff7ec",
    "activityBar.activeBackground": "#735A3C33",
    "activityBar.activeBorder": "#735A3C",
    // ---------------------------
    // Sidebar
    // ---------------------------
    "sideBar.background": "#ffe4bc",
    "sideBar.foreground": "#7b623e",
    "sideBar.border": "#ff976700",
    "sideBar.dropBackground": "#ffe4bc",
    "sideBarTitle.foreground": "#7b623e",
    "sideBarTitle.background": "#ffaa76",
    "sideBarSectionHeader.background": "#ffaa7665",
    "sideBarSectionHeader.foreground": "#7b623e",
    // ---------------------------
    // Status Bar
    // ---------------------------
    "statusBar.background": "#ffaa76",
    "statusBar.foreground": "#735A3C",
    "statusBar.border": "#ff976700",
    "statusBar.debuggingBackground": "#ffe4bc",
    "statusBar.debuggingForeground": "#e9498150",
    "statusBar.debuggingBorder": "#e94981af",
    "statusBar.noFolderForeground": "#87a7ab",
    "statusBar.noFolderBackground": "#ffe4bc",
    "statusBar.noFolderBorder": "#ffe4bc",
    "statusBarItem.activeBackground": "#dfeff1",
    "statusBarItem.hoverBackground": "#d1e8eb",
    "statusBarItem.prominentBackground": "#c1d4d7",
    "statusBarItem.prominentHoverBackground": "#bfdee3",
    // ---------------------------
    // Button
    // ---------------------------
    "button.background": "#099",
    "button.foreground": "#f1f1f1",
    "button.hoverBackground": "#0cc",
    // ---------------------------
    // Dropdown
    // ---------------------------
    "dropdown.background": "#fff7ec",
    "dropdown.border": "#fff7ec",
    "dropdown.foreground": "#005661",
    // ---------------------------
    // Editor Marker Navigation
    // ---------------------------
    "editorMarkerNavigation.background": "#3a3a5e29",
    "editorMarkerNavigationError.background": "#ff2d19",
    "editorMarkerNavigationWarning.background": "#e69533",
    // ---------------------------
    // Errors and warnings
    // ---------------------------
    "editorError.border": "#fff7ec",
    "editorError.foreground": "#ff2d19",
    "editorWarning.border": "#fff7ec",
    "editorWarning.foreground": "#e69533",
    "editorInfo.border": "#fff7ec",
    "editorInfo.foreground": "#00b395",
    "editorHint.border": "#58cc6d00",
    "editorHint.foreground": "#58cc6d",
    // ---------------------------
    // Editor Groups and Tabs
    // ---------------------------
    "editorGroup.emptyBackground": "#b8ae9333",
    "editorGroup.border": "#f0e7d1",
    "editorGroup.dropBackground": "#b8ae9333",
    // ---------------------------
    // Editor Group Header
    // ---------------------------
    "editorGroupHeader.noTabsBackground": "#ffe4bc",
    "editorGroupHeader.tabsBackground": "#ffe4bc",
    "editorGroupHeader.tabsBorder": "#ffe4bc00",
    // ---------------------------
    // Editor Tabs
    // ---------------------------
    "tab.activeBackground": "#fff7ec",
    "tab.unfocusedActiveBackground": "#f7f2e3",
    "tab.activeForeground": "#735A3C",
    "tab.border": "#e6d7b2",
    "tab.inactiveBackground": "#ffe4bc",
    "tab.inactiveForeground": "#7b623e",
    "tab.unfocusedActiveForeground": "#7b623e",
    "tab.unfocusedInactiveForeground": "#7b623e",
    "tab.activeBorderTop": "#00b395",
    "tab.activeModifiedBorder": "#00b368",
    "tab.activeBorder": "#fff7ec",
    "tab.unfocusedActiveBorder": "#fff7ec00",
    "tab.unfocusedHoverBackground": "#735A3C21",
    // ---------------------------
    // Text Colors
    // ---------------------------
    "textBlockQuote.background": "#ffe4bc",
    "textBlockQuote.border": "#00899e",
    "textCodeBlock.background": "#ffe4bc",
    "textLink.activeForeground": "#00b395",
    "textLink.foreground": "#00b395",
    "textPreformat.foreground": "#B65C7A",
    "textSeparator.foreground": "#ffe4bc",
    // ---------------------------
    // Welcome Page
    // ---------------------------
    "walkThrough.embeddedEditorBackground": "#ffe4bc",
    "welcomePage.buttonBackground": "#ffe4bc",
    "welcomePage.buttonHoverBackground": "#e1e0d0",
    // ---------------------------
    // Input Control
    // ---------------------------
    "input.background": "#fff7ec",
    "input.border": "#f2edde",
    "input.foreground": "#6a7a7c",
    "input.placeholderForeground": "#9fabad",
    "inputOption.activeBorder": "#735A3C",
    "inputValidation.errorBackground": "#ff2d1941",
    "inputValidation.errorBorder": "#ff2d19",
    "inputValidation.infoBackground": "#00b395cc",
    "inputValidation.infoBorder": "#00b395",
    "inputValidation.warningBackground": "#ffa587cc",
    "inputValidation.warningBorder": "#ffa487",
    // ---------------------------
    // Editor Widgets
    // ---------------------------
    "editorWidget.background": "#f2edde",
    "editorWidget.border": "#ff976700",
    "editorHoverWidget.background": "#f2edde",
    "editorHoverWidget.border": "#ff976700",
    "editorSuggestWidget.background": "#f2edde",
    "editorSuggestWidget.border": "#ff976700",
    "editorSuggestWidget.foreground": "#6a7a7c",
    "editorSuggestWidget.highlightForeground": "#735A3C",
    "editorSuggestWidget.selectedBackground": "#dbfaff",
    // ---------------------------
    // Gutter
    // ---------------------------
    "editorGutter.background": "#fff7ec",
    "editorGutter.addedBackground": "#8ce99a",
    "editorGutter.deletedBackground": "#ff2d19",
    "editorGutter.modifiedBackground": "#B65C7A",
    // ---------------------------
    // Selection Colors
    // ---------------------------
    "editor.selectionBackground": "#ade2eb77",
    "editor.selectionHighlightBackground": "#14a5ff33",
    "editor.selectionHighlightBorder": "#14a5ff00",
    "editor.inactiveSelectionBackground": "#ade2eb55",
    "editor.wordHighlightStrongBackground": "#b5890027",
    "editor.wordHighlightStrongBorder": "#b5890000",
    "editor.wordHighlightBackground": "#B65C7A22",
    "editor.wordHighlightBorder": "#B65C7A00",
    "editor.findMatchBackground": "#8ce99a55",
    "editor.findMatchBorder": "#8ce99a00",
    "editor.findMatchHighlightBackground": "#148f9f33",
    "editor.findMatchHighlightBorder": "#148f9f00",
    "editor.findRangeHighlightBackground": "#99e62a55",
    "editor.findRangeHighlightBorder": "#58CC6D00",
    "editor.hoverHighlightBackground": "#735A3C3f",
    "editor.lineHighlightBackground": "#ffe6bfcc",
    "editor.lineHighlightBorder": "#ffe6bf00",
    "editor.rangeHighlightBackground": "#f1e9d5a1",
    "editorLink.activeForeground": "#14a5ff",
    "editorWhitespace.foreground": "#d3cec5bb",
    "editorIndentGuide.background": "#d3cec5aa",
    "editorIndentGuide.activeBackground": "#88adc3",
    "editorBracketMatch.background": "#735A3C20",
    "editorBracketMatch.border": "#735A3C",
    "editorRuler.foreground": "#f1e6d0",
    // ---------------------------
    // Code Lens
    // ---------------------------
    "editorCodeLens.foreground": "#77aaca",
    // ---------------------------
    // Integrated Terminal Colors
    // ---------------------------
    "terminal.ansiBlack": "#003b42",
    "terminal.ansiRed": "#e34e1c",
    "terminal.ansiGreen": "#00b368",
    "terminal.ansiYellow": "#f49725",
    "terminal.ansiBlue": "#0094f0",
    "terminal.ansiMagenta": "#ff5792",
    "terminal.ansiCyan": "#00bdd6",
    "terminal.ansiWhite": "#8ca6a6",
    "terminal.ansiBrightBlack": "#004d57",
    "terminal.ansiBrightRed": "#ff2d19",
    "terminal.ansiBrightGreen": "#00d17a",
    "terminal.ansiBrightYellow": "#ff8c00",
    "terminal.ansiBrightBlue": "#0fa3ff",
    "terminal.ansiBrightMagenta": "#ff6b9f",
    "terminal.ansiBrightCyan": "#00cbe6",
    "terminal.ansiBrightWhite": "#bbc3c4",
    "terminal.background": "#fce2bb",
    "terminal.foreground": "#005661",
    "terminalCursor.background": "#fce2bb",
    "terminalCursor.foreground": "#005661",
    // ---------------------------
    // Merge
    // ---------------------------
    "merge.border": "#fff7ec00",
    "merge.currentContentBackground": "#33e7ff33",
    "merge.currentHeaderBackground": "#33e7ff55",
    "merge.incomingContentBackground": "#9d92f233",
    "merge.incomingHeaderBackground": "#9d92f255",
    "merge.commonContentBackground": "#ffc18033",
    "merge.commonHeaderBackground": "#ffc18055",
    "editorOverviewRuler.currentContentForeground": "#33e7ff55",
    "editorOverviewRuler.incomingContentForeground": "#9d92f255",
    "editorOverviewRuler.commonContentForeground": "#ffc18055",
    "editorOverviewRuler.border": "#fff7ec",
    // ---------------------------
    // Notification Colors
    // ---------------------------
    "notificationCenter.border": "#f2edde",
    "notificationCenterHeader.foreground": "#005661",
    "notificationCenterHeader.background": "#f2edde",
    "notificationToast.border": "#f2edde",
    "notifications.foreground": "#005661",
    "notifications.background": "#f2edde",
    "notifications.border": "#f2edde",
    "notificationLink.foreground": "#005661",
    // ---------------------------
    // Diff
    // ---------------------------
    "diffEditor.insertedTextBackground": "#e6580030",
    "diffEditor.removedTextBackground": "#BB1F0522",
    // ---------------------------
    // Debug
    // ---------------------------
    "debugToolBar.background": "#ffe4bc",
    "debugExceptionWidget.background": "#ffe4bc",
    "debugExceptionWidget.border": "#00899e",
    // ---------------------------
    // Extensions
    // ---------------------------
    "extensionButton.prominentBackground": "#099",
    "extensionButton.prominentForeground": "#e5f5f5",
    "extensionButton.prominentHoverBackground": "#0cc",
    focusBorder: "#f2edde",
    foreground: "#005661",
    // ---------------------------
    // Panel
    // ---------------------------
    "panel.background": "#fce2bb",
    "panel.border": "#00b395",
    "panelTitle.activeBorder": "#00b395",
    "panelTitle.activeForeground": "#735A3C",
    "panelTitle.inactiveForeground": "#7b623e",
    // ---------------------------
    // Peek View Colors
    // ---------------------------
    "peekView.border": "#735A3C",
    "peekViewEditor.background": "#fff7e5",
    "peekViewEditor.matchHighlightBackground": "#148f9f33",
    "peekViewEditor.matchHighlightBorder": "#148f9f79",
    "peekViewEditorGutter.background": "#fff7e5",
    "peekViewResult.background": "#ffe4bc",
    "peekViewResult.fileForeground": "#B65C7A",
    "peekViewResult.lineForeground": "#87a7ab",
    "peekViewResult.matchHighlightBackground": "#f2edde",
    "peekViewResult.selectionBackground": "#f2edde",
    "peekViewResult.selectionForeground": "#6a7a7c",
    "peekViewTitle.background": "#ffe4bc",
    "peekViewTitleDescription.foreground": "#87a7ab",
    "peekViewTitleLabel.foreground": "#B65C7A",
    // ---------------------------
    // Progress Bar
    // ---------------------------
    "progressBar.background": "#00b395",
    // ---------------------------
    // Scroll Bar
    // ---------------------------
    "scrollbar.shadow": "#00000055",
    "scrollbarSlider.activeBackground": "#735A3Cad",
    "scrollbarSlider.background": "#6a90955b",
    "scrollbarSlider.hoverBackground": "#735A3C62",
    // ---------------------------
    // Git status colors in File Explorer
    // ---------------------------
    "gitDecoration.addedResourceForeground": "#5d9936",
    "gitDecoration.modifiedResourceForeground": "#e65800",
    "gitDecoration.deletedResourceForeground": "#ff2d19",
    "gitDecoration.untrackedResourceForeground": "#00b395",
    "gitDecoration.ignoredResourceForeground": "#7b623eaa",
    "gitDecoration.conflictingResourceForeground": "#B65C7A",
    // ---------------------------
    // Quick Picker
    // ---------------------------
    "pickerGroup.border": "#00b395",
    "pickerGroup.foreground": "#735A3C",
    // ---------------------------
    // Lists and Trees
    // ---------------------------
    "list.activeSelectionBackground": "#ffc998",
    "list.activeSelectionForeground": "#005661",
    "list.dropBackground": "#cdcbb2",
    "list.focusBackground": "#bee3ea",
    "list.focusForeground": "#005661",
    "list.highlightForeground": "#735A3C",
    "list.hoverBackground": "#ffc087",
    "list.hoverForeground": "#005661",
    "list.inactiveFocusBackground": "#c9eaed",
    "list.inactiveSelectionBackground": "#ffcb9c",
    "list.inactiveSelectionForeground": "#452f1b",
    "list.errorForeground": "#c9481d",
    "list.warningForeground": "#e07a52",
    "listFilterWidget.background": "#ffcda0",
    "listFilterWidget.outline": "#e65800",
    "listFilterWidget.noMatchesOutline": "#ff2d19",
    "tree.indentGuidesStroke": "#d3cec5",
    // ---------------------------
    // Settings Editor Colors
    // ---------------------------
    "settings.headerForeground": "#004d57",
    "settings.modifiedItemIndicator": "#00bd23",
    "settings.dropdownListBorder": "#ade2eb88",
    "settings.dropdownBackground": "#f2edde",
    "settings.dropdownForeground": "#0bb",
    "settings.dropdownBorder": "#f2edde",
    "settings.checkboxBackground": "#f2edde",
    "settings.checkboxForeground": "#0bb",
    "settings.checkboxBorder": "#f2edde",
    "settings.textInputBackground": "#f2edde",
    "settings.textInputForeground": "#0bb",
    "settings.textInputBorder": "#f2edde",
    "settings.numberInputBackground": "#f0e7d1",
    "settings.numberInputForeground": "#5842ff",
    "settings.numberInputBorder": "#f0e7d1",
    // ---------------------------
    // Breadcrumbs
    // ---------------------------
    "breadcrumb.foreground": "#7b623e",
    "breadcrumb.background": "#fff7ec",
    "breadcrumb.focusForeground": "#735A3C",
    "breadcrumb.activeSelectionForeground": "#005661",
    "breadcrumbPicker.background": "#f2edde",
    // ---------------------------
    // Title bar
    // Note: These colors are currently only supported on macOS.
    // ---------------------------
    "titleBar.activeBackground": "#ffe4bc",
    "titleBar.activeForeground": "#005661",
    "titleBar.inactiveBackground": "#ffe4bc",
    "titleBar.inactiveForeground": "#7b623e",
    // ---------------------------
    // Custom title bar and menus
    // Note: These colors are currently only supported on Windows and Linux.
    // ---------------------------
    "menu.background": "#f2edde",
    "menu.foreground": "#7b623e",
    "menu.selectionBackground": "#d2f3f9",
    "menu.selectionForeground": "#735A3C",
    "menu.selectionBorder": "#d2f3f9",
    "menubar.selectionBackground": "#d2f3f9",
    "menubar.selectionForeground": "#735A3C",
    "menubar.selectionBorder": "#d2f3f9",
    // ---------------------------
    // Snippets
    // ---------------------------
    "editor.snippetTabstopHighlightBackground": "#fdefd3",
    "editor.snippetTabstopHighlightBorder": "#fdf3dd",
    "editor.snippetFinalTabstopHighlightBackground": "#fdefd3",
    "editor.snippetFinalTabstopHighlightBorder": "#fdf3dd",
    // ---------------------------
    // Minimap
    // ---------------------------
    "minimap.findMatchHighlight": "#735A3Caa",
    "minimap.errorHighlight": "#ff2d19ee",
    "minimap.warningHighlight": "#e69533ee",
    "minimapGutter.addedBackground": "#5d9936",
    "minimapGutter.modifiedBackground": "#e65800",
    "minimapGutter.deletedBackground": "#ff2d19",
    "minimap.background": "#fff7ec99",
  },
  tokenColors: syntax,
});
